version: '3.7'

networks:
  filup-local-net:
    name: filup-local-net

volumes:
  odata1-1:
  odata1-2:
  odata2-1:
  odata2-2:
  portainer_data:

x-volume-localtime: &volume-localtime
  "/etc/localtime:/etc/localtime:ro"

x-default-service: &default-service
  init: true
  restart: unless-stopped
  networks:
    - filup-local-net
  volumes:
    - *volume-localtime

x-minio-common: &minio-common
  <<: *default-service
  image: minio/minio:RELEASE.2022-06-17T02-00-35Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - odata1-1:/data1
      - odata1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - odata2-1:/data1
      - odata2-2:/data2

  minio:
    <<: *default-service
    image: nginx:1.21.1-alpine
    volumes:
      - ./nginx/minio/minio.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2

  nats:
    <<: *default-service
    image: library/nats:2.2.1-alpine
    ports:
      - 4222:4222
      - 8222:8222
