// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/satmaelstorm/filup/internal/infrastructure/appctx"
	"github.com/satmaelstorm/filup/internal/infrastructure/config"
	"github.com/satmaelstorm/filup/internal/infrastructure/logs"
	"github.com/satmaelstorm/filup/internal/infrastructure/web"
	"github.com/satmaelstorm/filup/internal/infrastructure/web/routes"
)

// Injectors from wire.go:

func InitWebServer() *web.Server {
	coreContext := appctx.ProvideContext()
	configuration := config.ProvideConfig()
	loggers := logs.ProvideLoggers(configuration)
	router := routes.ProvideRoutes(loggers)
	server := web.ProvideWebServer(coreContext, router, configuration, loggers)
	return server
}
