http:
  port: 8080
  timeout: 30

logs:
  trace:
    prefix: TRACE
  debug:
    prefix: DEBUG
  error:
    prefix: ERROR
    metricsOpts:
      name: error
  critical:
    prefix: CRITICAL
    metricsOpts:
      name: critical
  STD:
    prefix: STD

storage:
  type: s3
  s3:
    endpoint: localhost:9000
    useSSL: false
    region: eu-central-1
    maxLifeTime: 60
    buckets:
      meta: "filup-meta"
      parts: "filup-parts"
      final: "filup"
    credentials:
      key: minio
      secret: minio123

uploader:
  uuidNodeId: ""
  infoFieldName: "_uploader_info"
  chunkLength: 52428800 #50Mb
  callbackBefore:
  callbackAfter:
  httpTimeout: 5
  httpRetries: 3
  composerWorkers: 5

caches:
  parts:
    size: 100

queue:
  type: "nats"
  uri: "nats://localhost:4222"
  maxLifeTime: 5
